In [13]:
import numpy as np

# Create a random 5x5 ndarray
X = np.random.random((5, 5))

# Normalize X (subtract the mean and divide by the standard deviation)
X_normalized = (X - X.mean()) / X.std()

# Save the normalized ndarray as X_normalized.npy
np.save('X_normalized.npy', X_normalized)

# Show the original and normalized arrays for verification
print('Original Array X: \n' , X)
print('\nNormalized Array:\n' , X_normalized)


Original Array X: 
 [[0.06233989 0.62225928 0.48863472 0.97286363 0.68642289]
 [0.34679282 0.88293833 0.59329993 0.82859883 0.15943695]
 [0.63348813 0.9887559  0.44295775 0.12831277 0.74899206]
 [0.23986518 0.80805352 0.45567884 0.64284891 0.56108597]
 [0.65711104 0.78884491 0.01874279 0.11296986 0.91626172]]

Normalized Array:
 [[-1.6825682   0.24338238 -0.21624502  1.44935357  0.46408547]
 [-0.70413757  1.14003817  0.14377114  0.953127   -1.34858413]
 [ 0.28200617  1.50401809 -0.37335974 -1.45564176  0.67930418]
 [-1.07193576  0.88245743 -0.32960313  0.31420437  0.032965  ]
 [ 0.36326171  0.81638573 -1.83252879 -1.50841666  1.25466037]]


In [17]:
import numpy as np

# Get the squares of first 100 positive integers
s = np.arange(1,101) ** 2

# Make the array into a 10 x 10 matrix
A = s.reshape(10,10)

# Determine all the elements that are divisible by 3
div_by_3 = A[A % 3 == 0]

# Show the original array and the array of elements by 3 for verificatio\n
print('Original Array:\n', A)
print('\nElements Divisible by 3:\n', div_by_3)


Original Array:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
